"""empty message

Revision ID: 3e38d7e49da4
Revises: 
Create Date: 2021-04-15 16:27:40.979898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e38d7e49da4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=1000), nullable=True),
    sa.Column('last_name', sa.String(length=1000), nullable=True),
    sa.Column('email', sa.String(length=1000), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=1000), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=1000, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=1000, scale=2), nullable=True),
    sa.Column('grandsubtotal', sa.Numeric(precision=1000, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=1000, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=1000, scale=2), nullable=True),
    sa.Column('ord_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(length=1000), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=1000, scale=2), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=1000, scale=2), nullable=True),
    sa.Column('quantity_instock', sa.Integer(), nullable=True),
    sa.Column('quantity_sold', sa.Integer(), nullable=True),
    sa.Column('supplier', sa.String(length=1000), nullable=True),
    sa.Column('perishables', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=1000), nullable=True),
    sa.Column('photo', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    op.drop_table('subscriber')
    op.drop_table('inventory')
    op.drop_table('customer_orders')
    op.drop_table('complaint')
    # ### end Alembic commands ###
