"""empty message

Revision ID: 54fb5675650f
Revises: 7b43c5582638
Create Date: 2021-04-15 00:56:35.777796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54fb5675650f'
down_revision = '7b43c5582638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_orders', sa.Column('ord_date', sa.DateTime(), nullable=True))
    op.add_column('customer_orders', sa.Column('orderid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_orders', 'orderid')
    op.drop_column('customer_orders', 'ord_date')
    # ### end Alembic commands ###
