"""empty message

Revision ID: 7b43c5582638
Revises: d9845e430f47
Create Date: 2021-03-26 12:12:46.950702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b43c5582638'
down_revision = 'd9845e430f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=1000), nullable=True),
    sa.Column('last_name', sa.String(length=1000), nullable=True),
    sa.Column('email', sa.String(length=1000), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=1000), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=1000, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=1000, scale=2), nullable=True),
    sa.Column('grandsubtotal', sa.Numeric(precision=1000, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=1000, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=1000, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_orders')
    # ### end Alembic commands ###
