"""empty message

Revision ID: a930cbe05aa9
Revises: c6027f9c4b33
Create Date: 2021-04-15 01:06:40.664999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a930cbe05aa9'
down_revision = 'c6027f9c4b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_orders', sa.Column('ord_date3', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('customer_orders', 'ord_date2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_orders', sa.Column('ord_date2', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('customer_orders', 'ord_date3')
    # ### end Alembic commands ###
