"""empty message

Revision ID: c6027f9c4b33
Revises: 1a175aef56e2
Create Date: 2021-04-15 01:05:19.118453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6027f9c4b33'
down_revision = '1a175aef56e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_orders', sa.Column('ord_date2', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_orders', 'ord_date2')
    # ### end Alembic commands ###
